# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/CPS_Domani/Dockerfile'
        tags: |
          $(tag)
    - task: JFrogBuildPromotion@1
      inputs:
        artifactoryConnection: 'PBM Jfrog Artifactory Publish'
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
        targetRepo: 'pbm-docker-local'
        status: 'Released'
        includeDependencies: true
        copy: false
        dryRun: true

    
    
    